### ISSUE TITLE
Question: Are the docs current?

### ISSUE THREAD

**Issue by simontegg** [decc/twenty-fifty-new-look#2]
Hi @tamc,

after running the bash script in `util` and compiling `model/model.xlsx` to generate `model/libmodel.so`  then running `middleman`, the app loads at `:4567` but I get the `dataRequester.js` error `Sorry, there was an error connecting to the server.`. Does middleman start the api server or am I missing something obvious?

**Comment by tamc** [comment]
Sorry. They weren't. They are now (I hope).

**Comment by simontegg** [comment]
Thanks!  Appreciated.

**Comment by PhilipSargent** [comment]
----- Original Message ----- 
  From: postmaster@OP1.PSN360.FCOS.GSI.GOV.UK 
  To: philip.sargent@gmail.com 
  Sent: Monday, October 12, 2015 11:25 PM
  Subject: Undeliverable: checksum for .xlsx

  Delivery has failed to these recipients or groups:

  philipsargent@decc.gsi.gov.uk
  The email address you entered couldn't be found. Please check the recipient's email address and try to resend the message. If the problem continues, please contact your helpdesk.

  Diagnostic information for administrators:

  Generating server: ROP1VEXMB04.OP1.PSN360.FCOS.GSI.GOV.UK

  philipsargent@decc.gsi.gov.uk
  Remote Server returned '550 5.1.1 RESOLVER.ADR.RecipNotFound; not found'

  Original message headers:

Received: from ROP1VEXAS02.OP1.PSN360.FCOS.GSI.GOV.UK (10.44.159.55) by
 ROP1VEXMB04.OP1.PSN360.FCOS.GSI.GOV.UK (10.44.159.58) with Microsoft SMTP
 Server (TLS) id 15.0.995.29; Mon, 12 Oct 2015 22:25:32 +0000
Received: from RGSAEVMG2.core-rest.local (10.44.6.51) by
 ROP1VEXAS02.OP1.PSN360.FCOS.GSI.GOV.UK (10.44.158.55) with Microsoft SMTP
 Server id 15.0.995.29 via Frontend Transport; Mon, 12 Oct 2015 22:25:32 +0000
X-AuditID: 0a2c0633-f798d6d000005689-f3-561c335be699
Received: from mx.hosting-e.gsi.gov.uk ( [51.63.249.43])
    by RGSAEVMG2.core-rest.local (Symantec Messaging Gateway) with SMTP id 1E.93.22153.B533C165; Mon, 12 Oct 2015 23:25:31 +0100 (BST)
Received: from avil0.sym.gsi.gov.uk ([51.63.153.198] helo=server-1.bemta-100.messagelabs.com)
    by mx.hosting-e.gsi.gov.uk with esmtp (Exim 4.83)
    (envelope-from philip.sargent@gmail.com)
    id 1ZllX9-0002NN-2t
    for philipsargent@decc.gsi.gov.uk; Mon, 12 Oct 2015 23:25:31 +0100
Received: from [62.208.159.157:34444] by server-1.bemta-100.messagelabs.com id CF/E8-01813-B533C165; Mon, 12 Oct 2015 22:25:31 +0000
X-Env-Sender: philip.sargent@gmail.com
X-Msg-Ref: server-9.tower-221.messagelabs.com!1444688730!25914436!1
X-Originating-IP: [209.85.212.174]
X-SpamReason: No, hits=0.4 required=7.0 tests=DATE_IN_PAST_48_96
X-StarScan-Received:
X-StarScan-Version: 7.13; banners=-,-,decc.gsi.gov.uk
X-VirusChecked: Checked
Received: (qmail 47001 invoked from network); 12 Oct 2015 22:25:30 -0000
Received: from mail-wi0-f174.google.com (HELO mail-wi0-f174.google.com) (209.85.212.174)
  by server-9.tower-221.messagelabs.com with AES128-GCM-SHA256 encrypted SMTP; 12 Oct 2015 22:25:30 -0000
Received: by wicge5 with SMTP id ge5so167127306wic.0
        for philipsargent@decc.gsi.gov.uk; Mon, 12 Oct 2015 15:25:30 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=message-id:from:to:cc:references:subject:date:mime-version
         :content-type:content-transfer-encoding;
        bh=pVUyGS0KdNCmtv3OjRgUI6IoBADE5u+X0fTBXfh2kzM=;
        b=loAv7KKQy8YsuioqPUCfOmEczVcL6MJXjMkwpA6GiaSTJVpp9pst+d0BBvFAMZVGo1
         E4lqmS2rSMCmmPY5VfaK3uIFVJ8TNN9cElg1B+52oWJbKfK5nSlNZ7T5S60k/TEuJuKX
         aX5mt3mHO8uq7x5Cf55kld3kPSp1g5T+l2ptVsSDaAQPfY/SzF3d6daM5BzNmgb17jCa
         JCgcsRVUOe6+6znPzefM1ftLAmtNJbW7A3Ci44+VlrXRkqOeG849xe8E5KRssTQStB1X
         E+sapnGfB7+XI7dIYzD5qNF0NH7AKjbIlX9OWZOteTVrJHnRqkMqm1bKIZCmP9t3+bH7
         Myqw==
X-Received: by 10.180.198.178 with SMTP id jd18mr17285281wic.34.1444688730158;
        Mon, 12 Oct 2015 15:25:30 -0700 (PDT)
Received: from Maya (cpc5-cmbg4-0-0-cust987.5-4.cable.virginm.net. [86.14.235.220])
        by smtp.gmail.com with ESMTPSA id qq4sm22191909wjc.14.2015.10.12.15.25.29
        (version=TLSv1/SSLv3 cipher=OTHER);
        Mon, 12 Oct 2015 15:25:29 -0700 (PDT)
Message-ID: <016601d1053c$ed1c8160$3801a8c0@Maya>
From: "Philip Sargent (GMail)" philip.sargent@gmail.com
To: Tom Counsell tom@counsell.org
CC: philipsargent@decc.gsi.gov.uk
References: 6C69E2EDA715496EAB1042EA97A192DF@klebos.net
 0B527534378D4044BC2247250F162AC1@fastmail.fm
Subject: checksum for .xlsx
Date: Fri, 9 Oct 2015 17:33:56 +0100
MIME-Version: 1.0
Content-Type: text/plain; format=flowed; charset="UTF-8"; reply-type=original
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.2180
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.2180
X-Brightmail-Tracker: H4sIAAAAAAAAA+NgFtrIKsWRWlGSWpSXmKPExsVibP9TWzfaWCbM4OAEAYuDN1tYHBg9Gi5d
    ZwtgjOKySUnNySxLLdK3S+DKuHX7OVvBE/aKv92/WRoYZ7J1MXJySAiYSMx7844RwhaTuHBv
    PVCci0NIYC+jxJfOhUwgCSGBmUwSm5ZYQiRaGCUe985mgehQk2g78RhqkrPE+2Wb2SFsJYk/
    Zy4A1XAA2Q4SZ2bzQpgiEpObrCBMU4mfq6ohisUlJi9cyQyxyUNiwY+jUCccZpSY/GsiM4TT
    wShxfM9xRhCHRWApq8TZB5+h9tZKfDzYwgjR3sQk8f2QOojNK2AocbnjLBPINjYBa4nuhaIg
    YREBVYnOla+YQcLMAsoSRzutIDozJP5ueAk2UVhAWuLYmQawT1gEVCQO9l1ghpgoKHFy5hOw
    z5kFgiVap59kh7DlJba/ncMMcQ2vxIz2p9DQkZRoXv0IyjaS+DX3GDScLSSmvlzOOoFRYRaS
    sbOQjJ2FZOwCRuZVjJJB7sGOrmG+7kZ6yflFqbpFqcUlejn5yYk5mxiBiYBLh814B+PjNU6H
    GAU4GJV4eDm2SIUJsSaWFVfmHmKU4GBWEuFVmigdJsSbklhZlVqUH19UmpNafIhRmoNFSZz3
    fE9XqJBAemJJanZqakFqEUyWiYPzFKOilDivk5FMmJBAcUFibkZpXglMASz5XWKUlRLmZWRg
    YBDiAerOzSxBlZdqYJR5uGRj9sKrPvU7Uj9rSGbWlltsC5sZwHuo/YLL+bXWnr4bdgZIi4fu
    PF7nGcY4642g781lqTqb+rLENhZoz97txiT88BtL29SytG9nNgu/iwnduTtqultko2LBf/8H
    e4+HL7or+e4Em/ejDVp/UpWen2fNEXI62rtllsSr0gDD8iUeK5wfJCuxFGckGmoxFxUnAgAb
    VVzLRAMAAA==
Return-Path: philip.sargent@gmail.com
