### ISSUE TITLE
Its not obvious how pathwayStringIndices map to input choices

### ISSUE THREAD

**Issue by simontegg** [decc/twenty-fifty-new-look#3]
Presumably a `pathWayStringIndex` of 5 in a pathway action in  `data/pathwayData.js` will map to the 5th row of spreadsheet?

![](http://i.imgur.com/D5fWTm8.png)

**Comment by tamc** [comment]
It is an index to the position in the named range 'input.choices' (i.e., zero is the first row in that named range) in the Excel spreadsheet, after all the rows marked with a zero have been excluded.

**Comment by simontegg** [comment]
Does this mean that the intersection between the subtitle rows and the "Your Choice" column must be marked with a zero before compiling for the mappings to work correctly?

For clarity, the "forestry" input choice in the following example has a `pathwayStringIndex` of 4? Ie the zero-indexed 5th item after the zero adjacent to the subtitle "Agricultural Land use" has been eliminated.

![](http://i.imgur.com/AWnSlRK.png)

Thanks for your help. I know this might seem obvious but someone else has developed this version of the spreadsheet and I'm just getting familiar with it.
